# Generated by Django 5.1.7 on 2026-03-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_irrigationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddata',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fielddata',
            name='irrigationType',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='fielddata',
            name='soilType',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
